### ISSUE TITLE
ROS 2 support

### ISSUE THREAD

**Issue by ipa-nhg** [ipa320/RosTooling#109]
The ROS2 support has to be considered for the two main models of the ROS tooling and their associated tools and features:

# Ros model
- [x] Metamodel adaptation or extension : In principle, and for simple use cases, this shouldn't be required. The communication architecture (core of the ROS metamodel) is the same for ROS1 and ROS2 :heavy_exclamation_mark:LOW PRIORITY
- [x] Static code analysis and auto-extraction of the model : HAROS supports already ROS2 (https://github.com/git-afsantos/haros/pull/83) , the ros-model-cloud scripts and the infrastructure has to be updated issue open: https://github.com/ipa320/ros-model-cloud/issues/29 :heavy_exclamation_mark::heavy_exclamation_mark:MEDIUM PRIORITY
- [ ] Rosgraph parser and auto-extraction of the model : the rosgraph_parser has to be ported to ROS2 https://github.com/ipa-nhg/ros_graph_parser :heavy_exclamation_mark::heavy_exclamation_mark:MEDIUM PRIORITY
- [x] Ros 2 nodes code auto-generation: a prototype of the ROS2 code generator is already working and released. It has to be completed #56 #75 :heavy_exclamation_mark:LOW PRIORITY

# RosSystem model
- [ ] Metamodel adaptation or extension: An extension of the model will be needed to be able to support the new concepts introduced for ROS2 , like lifecycles or the management of the cores. :heavy_exclamation_mark: :heavy_exclamation_mark: :heavy_exclamation_mark:HIGH PRIORITY
- [ ] Static code analysis and auto-extraction of the model: HAROS supports already ROS2 (https://github.com/git-afsantos/haros/pull/83) , the ros-model-cloud scripts and the infrastructure has to be updated issue open: https://github.com/ipa320/ros-model-cloud/issues/29  :heavy_exclamation_mark: :heavy_exclamation_mark:MEDIUM PRIORITY
- [ ] Rosgraph parser and auto-extraction of the model : the rosgraph_parser has to be ported to ROS2 https://github.com/ipa-nhg/ros_graph_parser  :heavy_exclamation_mark: :heavy_exclamation_mark:MEDIUM PRIORITY
- [ ] Ros 2 launch files auto-generation:  
  - [x] Create a template file for ROS2 launch files  :heavy_exclamation_mark: :heavy_exclamation_mark: :heavy_exclamation_mark:HIGH PRIORITY
  - [x] Develop of a new Xtend compiler plugin to generate ROS2 launch files based on the template  :heavy_exclamation_mark: :heavy_exclamation_mark: :heavy_exclamation_mark:HIGH PRIORITY
  - [ ] Update the method to trigger the generator. Currently for every valid rossystem model imported on the tooling it auto-generates the ROS packages that contains a ROS1 launch file. An option to generate ROS2 artifacts instead of the ROS1 ones has to be added, can this setting option be added in a intuitively way (without a reconfiguration of the compiler)? . Alternatively, OPTION A: the user can trigger the generator for each rossystem model ( "right-click" menu option for the *rossystem file format) or OPTION B: create a new toolbar button which open a   pop-up menu asking for the ROS1/2 option and trigger the generator for all the rossystem files of my project or my workspace. A new Xtend compiler  :heavy_exclamation_mark: :heavy_exclamation_mark:MEDIUM PRIORITY
  - [ ] Improve the launch file generator , see: https://docs.ros.org/en/foxy/Guides/Launch-files-migration-guide.html

**Comment by ipa-nhg** [comment]
Static code analysis and auto-extraction of the model: https://github.com/ipa320/ros-model-extractors

Ros 2 nodes code auto-generation: a prototype of the ROS2 code generator is already working and released. It has to be completed #56 #75 :heavy_exclamation_mark:LOW PRIORITY -> WIP: https://github.com/ipa320/ros-model/pull/130
